import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';import {onRequest} from '../functions/api/contact.js';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_verification.sql',import.meta.url),'utf8'));
const wrapper=sql=>({bind(...args){return {first:async()=>db.prepare(sql).get(...args),run:async()=>db.prepare(sql).run(...args)}}});
const env={DB:{prepare:wrapper,batch:async a=>Promise.all(a.map(x=>x.run()))},APP_ORIGIN:'https://vlk-infosec.com',TURNSTILE_SITE_KEY:'test',TURNSTILE_SECRET:'test',RATE_SECRET:'test-secret',GOOGLE_CLIENT_ID:'test',GOOGLE_CLIENT_SECRET:'test',GOOGLE_REFRESH_TOKEN:'test',MAIL_FROM:'sender@example.com',MAIL_TO:'owner@example.com'};
let sent=[],turnstileValid=true;
globalThis.fetch=async(url,options)=>{if(url.includes('siteverify'))return Response.json({success:turnstileValid,hostname:'vlk-infosec.com',action:'enquiry'});if(url.includes('oauth2'))return Response.json({access_token:'fake'});if(url.includes('gmail')){const raw=Buffer.from(JSON.parse(options.body).raw,'base64url').toString();sent.push(Buffer.from(raw.split('\r\n\r\n')[1],'base64').toString());return Response.json({id:'fake'});}throw Error('Unexpected network');};
const call=async(data,origin=env.APP_ORIGIN)=>{const r=await onRequest({env,request:new Request(env.APP_ORIGIN+'/api/contact',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(data)})});return {status:r.status,data:await r.json()}};
assert.equal((await call({action:'request',email:'user@example.com',turnstile:'ok'},'https://evil.example')).status,403);
assert.equal((await call({action:'request',email:'bad\r\nBcc:x',turnstile:'ok'})).status,400);
turnstileValid=false;assert.equal((await call({action:'request',email:'user@example.com',turnstile:'bad'})).status,403);turnstileValid=true;
const request=await call({action:'request',email:'user@example.com',turnstile:'ok'});assert.equal(request.status,200);const code=sent[0].match(/\b\d{6}\b/)[0];
const fields={name:'Test',email:'user@example.com',service:'general',context:'Test enquiry'};
assert.equal((await call({action:'submit',id:request.data.id,code:code==='000000'?'111111':'000000',fields})).status,400);
assert.equal((await call({action:'submit',id:request.data.id,code,fields:{...fields,email:'other@example.com'}})).status,400);
assert.equal((await call({action:'submit',id:request.data.id,code,fields})).status,200);
assert.equal(sent.length,2);assert.equal((await call({action:'submit',id:request.data.id,code,fields})).status,400);
const second=await call({action:'request',email:'user@example.com',turnstile:'ok'});const code2=sent[2].match(/\b\d{6}\b/)[0];for(let i=0;i<5;i++)assert.equal((await call({action:'submit',id:second.data.id,code:code2==='000000'?'111111':'000000',fields})).status,400);assert.equal((await call({action:'submit',id:second.data.id,code:code2,fields})).status,400);
const third=await call({action:'request',email:'user@example.com',turnstile:'ok'});db.prepare('UPDATE challenges SET expires=0 WHERE id=?').run(third.data.id);assert.equal((await call({action:'submit',id:third.data.id,code:sent[3].match(/\b\d{6}\b/)[0],fields})).status,400);
assert.equal((await call({action:'request',email:'user@example.com',turnstile:'ok'})).status,429);
console.log('PASS: same-origin, email validation, Turnstile rejection, code delivery, wrong code, email binding, successful submission, replay rejection, attempt limit, expiry, rate limit. Provider calls mocked; no emails sent.');
// SQL and script payloads remain inert data; identifiers and mail headers are constrained.
db.exec('DELETE FROM rate_limits; DELETE FROM challenges;');
const malicious="Robert'); DROP TABLE challenges;-- <img src=x onerror=alert(1)>";
const probe=await call({action:'request',email:'probe@example.com',turnstile:'ok'});
assert.equal(probe.status,200);
const probeCode=sent.at(-1).match(/\b\d{6}\b/)[0];
assert.equal((await call({action:'submit',id:"' OR 1=1 --",code:probeCode,fields})).status,400);
assert.equal((await call({action:'submit',id:probe.data.id,code:probeCode,fields:{name:malicious,email:'probe@example.com',service:'other',context:'<script>alert(1)</script>'}})).status,200);
assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='challenges'").get().name,'challenges');
assert.ok(sent.at(-1).includes(malicious));
assert.equal((await call({action:'request',email:'a@example.com\r\nBcc: victim@example.com',turnstile:'ok'})).status,400);
console.log('PASS: SQL injection payload does not alter schema; script/HTML payload stays plain email text; malicious challenge ID and email-header injection rejected.');
